# This file is purposefully not named pyproject.toml
# To enable a better development experience for contributors using the
# git repository as their source tree.
# During the sdist phase, this file is copied into the release tree
# under the name pyproject.toml
# See discussion in: https://github.com/scikit-image/scikit-image/pull/4920
# For a longer description of the usage scenerios.
[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.18",
    # AIX is IBM's variant of UNIX; Scipy uses special handling for it.
    # Therefore we decided to handle it in the same way.
    "numpy==1.15.1; python_version=='3.6' and platform_system!='AIX'",
    "numpy==1.15.1; python_version=='3.7' and platform_system!='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'",
    "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'",
    "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'",
]
